AspNetCoreMVC-EmpAppCRUD-master/Models/Employee.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmpApp.Models
{
    [Table("Employees")]
    public class Employee
    {

        [Key]        
       public int Id { get; set; }
       [Required]
       [StringLength(255)]
       public string Name { get; set; }
       public int Age { get; set; }
       public string Designation { get; set; }
       public List <Leave> Leaves { get; set; }

    }
}

AspNetCoreMVC-EmpAppCRUD-master/Models/ErrorViewModel.cs
using System;

namespace EmpApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspNetCoreMVC-EmpAppCRUD-master/Models/Leave.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmpApp.Models
{
    [Table("Leaves")]
    public class Leave
    {
        [Key]
        public int LeaveId { get; set; }
        [Required]
        public DateTime StartDate { get; set; }
        [Required]
        public DateTime EndDate { get; set; }
        public string ApprovalStatus { get; set; }
        public Employee Employee { get; set; }
    }
}

AspNetCoreMVC-EmpAppCRUD-master/Models/LeaveViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmpApp.Models
{
    public class LeaveViewModel
    {
        public int LeaveId { get; set; }
        public String EmployeeName { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public string ApprovalStatus { get; set; }
    }
}

AspNetCoreMVC-EmpAppCRUD-master/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Linq;
using EmpApp.Models;
using EmpApp.Persistance;
using Microsoft.AspNetCore.Mvc;

namespace EmpApp.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly AppDbContext context;

        public EmployeeController(AppDbContext context)
        {
            this.context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var emps = context.Employees.ToList();
            return View(emps);
        }
         [HttpGet]
        public IActionResult Create() { 
            return View();
        }

        [HttpPost]
        public IActionResult Create(Employee model) { 
            if (!ModelState.IsValid) return View(model);
            context.Add(model);
            context.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Edit(int id) { 
            var emp = context.Employees.Find(id);
            return View(emp);
        }

        [HttpPost]
        public IActionResult Edit(Employee model) { 
            if (!ModelState.IsValid) return View(model);
            context.Employees.Update(model);
            context.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Delete(int id){ 
           var emp = context.Employees.Find(id);
           context.Employees.Remove(emp);
           context.SaveChanges();
           return RedirectToAction("index");
        }
    }
}

AspNetCoreMVC-EmpAppCRUD-master/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EmpApp.Models;

namespace EmpApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AspNetCoreMVC-EmpAppCRUD-master/Controllers/LeaveController.cs
using EmpApp.Persistance;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmpApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmpApp.Controllers
{
    public class LeaveController:Controller
    {
        private readonly AppDbContext context;

        public LeaveController(AppDbContext context)
        {
            this.context = context;
        }
        [HttpGet]
        public IActionResult Index()
        {
           var leaves = (from e in context.Employees
                          join l in context.Leaves
                          on e.Id equals l.Employee.Id
                          select new
                          {
                              e.Name,
                              l.StartDate,
                              l.EndDate,
                              l.ApprovalStatus,
                              l.LeaveId
                          }).ToList();
            List<LeaveViewModel> LeaveViewModel = new List<LeaveViewModel>();
            foreach (var l in leaves){
                LeaveViewModel leave = new LeaveViewModel();
                leave.EmployeeName = l.Name;
                leave.StartDate = l.StartDate;
                leave.EndDate = l.EndDate;
                leave.ApprovalStatus = l.ApprovalStatus;
                leave.LeaveId = l.LeaveId;
                LeaveViewModel.Add(leave);

            }
            return View(LeaveViewModel);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Leave model)
        {
            if (!ModelState.IsValid) return View(model);
            context.Add(model);
            context.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var emp = context.Leaves.Find(id);
            return View(emp);
        }

        [HttpPost]
        public IActionResult Edit(Leave model)
        {
            if (!ModelState.IsValid) return View(model);
            context.Leaves.Update(model);
            context.SaveChanges();
            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var leave = context.Leaves.Find(id);
            context.Leaves.Remove(leave);
            context.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

AspNetCoreMVC-EmpAppCRUD-master/Views/Employee/Create.cshtml
@model EmpApp.Models.Employee

<br/><br/>
<form asp-action="Create" method="Post">
     <div class="form-horizontal">
            <div class="row"> 
                <div class="form-group">  
                            <label asp-for="Name" class="col-lg-2 col-sm-3 control-label"></label>             
                            <div class="col-lg-3">  
                                <input asp-for="Name" class="form-control" />    
                                <span asp-validation-for="Name" class="text-danger"></span>               
                            </div>  
                </div> 

                <div class="form-group">  
                            <label asp-for="Age" class="col-lg-2 col-sm-3 control-label"></label>             
                            <div class="col-lg-3">  
                                <input asp-for="Age" class="form-control" />      
                                            
                            </div>  
                </div>  
            </div>
     </div>
        
     
        <input type="submit" value="Save" class="col-lg-2 col-md-offset-2 btn btn-success" /> <br/>

</form>

AspNetCoreMVC-EmpAppCRUD-master/Views/Employee/Edit.cshtml
@model EmpApp.Models.Employee

<br/><br/>
<form asp-action="Edit" method="Post">
     <div class="form-horizontal">
            <div class="row"> 
                <div class="form-group">  
                            <label asp-for="Name" class="col-lg-2 col-sm-3 control-label"></label>             
                            <div class="col-lg-3">  
                                <input asp-for="Name" class="form-control" />    
                                <span asp-validation-for="Name" class="text-danger"></span>               
                            </div>  
                </div> 

                <div class="form-group">  
                            <label asp-for="Age" class="col-lg-2 col-sm-3 control-label"></label>             
                            <div class="col-lg-3">  
                                <input asp-for="Age" class="form-control" />      
                                            
                            </div>  
                </div>  
            </div>
     </div>
        <input type="submit" value="Update" class="col-lg-2 col-md-offset-2 btn btn-success" /> <br/>

</form>

AspNetCoreMVC-EmpAppCRUD-master/Views/Employee/Index.cshtml
@model IEnumerable<EmpApp.Models.Employee>


 <div class="panel-body">  
        <div class="btn-group">  
            <a asp-action="Create"  class="btn btn-primary">  
                <i class="glyphicon glyphicon-plus"></i>  Add Employee  
            </a>  
        </div>  

<br/> <br/>


 <table class="table table-bordered table-striped table-condensed">  
            <thead>  
                <tr>  
                    <th>Name</th>                      
                    <th>Age</th>
                    <th>Action</th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in Model)  
                {  
                    <tr>  
                        <td>@Html.DisplayFor(modelItem => item.Name)</td>  
                        <td>@Html.DisplayFor(modelItem => item.Age)</td>                       
                        <td>  
                           <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">  
                                <i class="glyphicon glyphicon-pencil"></i>  Edit  
                            </a>  
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger" onclick ="return confirm('Are you sure you wish to delete ?');">  
                                <i class="glyphicon glyphicon-trash"></i>  Delete  
                            </a>  
                        </td>  
                    </tr>  
                }  
            </tbody>  
        </table>  

AspNetCoreMVC-EmpAppCRUD-master/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

AspNetCoreMVC-EmpAppCRUD-master/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AspNetCoreMVC-EmpAppCRUD-master/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>


<div class="container">
    <h2>USF Dining</h2>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/images/1.jpg" alt="Los Angeles" style="width:100%;">
            </div>

            <div class="item">
                <img src="~/images/2.jpg" alt="Chicago" style="width:100%;">
            </div>

            <div class="item">
                <img src="~/images/3.jpg" alt="New york" style="width:100%;">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

AspNetCoreMVC-EmpAppCRUD-master/Views/Leave/Create.cshtml
@model EmpApp.Models.Leave

<br/><br/>
<form asp-action="Create" method="Post">
     <div class="form-horizontal">
         <div class="row">
             <div class="form-group">
                 <label asp-for="StartDate" class="col-lg-2 col-sm-3 control-label"></label>
                 <div class="col-lg-3">
                     <input asp-for="StartDate" class="form-control" />
                     <span asp-validation-for="StartDate" class="text-danger"></span>
                 </div>
             </div>
             <div class="form-group">
                 <label asp-for="EndDate" class="col-lg-2 col-sm-3 control-label"></label>
                 <div class="col-lg-3">
                     <input asp-for="EndDate" class="form-control" />
                 </div>
             </div>

             <div class="form-group">
                 <label asp-for="ApprovalStatus" class="col-lg-2 col-sm-3 control-label" ></label>
                 <div class="col-lg-3">
                     <input asp-for="ApprovalStatus" class="form-control" value="Waiting Approval"/>
                 </div>
             </div>

         </div>
     </div>
        
     
        <input type="submit" value="Save" class="col-lg-2 col-md-offset-2 btn btn-success" /> <br/>

</form>

AspNetCoreMVC-EmpAppCRUD-master/Views/Leave/Edit.cshtml
@model EmpApp.Models.Employee

<br/><br/>
<form asp-action="Edit" method="Post">
     <div class="form-horizontal">
            <div class="row"> 
                <div class="form-group">  
                            <label asp-for="Name" class="col-lg-2 col-sm-3 control-label"></label>             
                            <div class="col-lg-3">  
                                <input asp-for="Name" class="form-control" />    
                                <span asp-validation-for="Name" class="text-danger"></span>               
                            </div>  
                </div> 

                <div class="form-group">  
                            <label asp-for="Age" class="col-lg-2 col-sm-3 control-label"></label>             
                            <div class="col-lg-3">  
                                <input asp-for="Age" class="form-control" />      
                                            
                            </div>  
                </div>  
            </div>
     </div>
        <input type="submit" value="Update" class="col-lg-2 col-md-offset-2 btn btn-success" /> <br/>

</form>

AspNetCoreMVC-EmpAppCRUD-master/Views/Leave/Index.cshtml
@model IEnumerable<EmpApp.Models.LeaveViewModel>


 <div class="panel-body">  
        <div class="btn-group">  
            <a asp-action="Create"  class="btn btn-primary">  
                <i class="glyphicon glyphicon-plus"></i>  Apply Leave
            </a>  
        </div>  

<br/> <br/>


 <table class="table table-bordered table-striped table-condensed">  
            <thead>  
                <tr> 
                    <th>Emp Name</th>
                    <th>StartDate</th>                      
                    <th>EndDate</th>
                    <th>Approval Status</th>  
                </tr>  
            </thead>  
            <tbody>  
                @foreach (var item in Model)  
                {  
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.EmployeeName)</td>
                    <td>@Html.DisplayFor(modelItem => item.StartDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.EndDate)</td>
                    <td>@Html.DisplayFor(modelItem => item.ApprovalStatus)</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.LeaveId" class="btn btn-info">
                            <i class="glyphicon glyphicon-pencil"></i>  Edit
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.LeaveId" class="btn btn-danger" onclick="return confirm('Are you sure you wish to delete ?');">
                            <i class="glyphicon glyphicon-trash"></i>  Delete
                        </a>
                    </td>
                </tr>  
                }  
            </tbody>  
        </table>  

AspNetCoreMVC-EmpAppCRUD-master/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Employee CRUD App</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Emp App</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Employee" asp-action="Index">Employee</a></li>
                    <li><a asp-area="" asp-controller="Leave" asp-action="Index">Leaves</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - dotnetT</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>